--------------------------------------------------------
--  File created - Monday-December-19-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COPART_FACILITY
--------------------------------------------------------

  CREATE TABLE "HR"."COPART_FACILITY" 
   (	"ZIPCODE" VARCHAR2(40 BYTE), 
	"CITY" VARCHAR2(40 BYTE), 
	"STATE" VARCHAR2(40 BYTE), 
	"ABBREVIATION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.COPART_FACILITY
SET DEFINE OFF;
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('93307','BAKERFIELD','CALIFORNIA','CA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('93725','FRESNO','CALIFORNIA','CA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('94545','HAYWARD','CALIFORNIA','CA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('90001','LOSANGELES','CALIFORNIA','CA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('94553','MARTINEZ','CALIFORNIA','CA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('880907','COLORADO SPRINGS','COLORADO','CO');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('880603','BRIGHTON','COLORADO','CO');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('06051','NEW BRITAIN','CONNECTICUT','CT');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('19973','SEAFORD','DDELAWARE','DE');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('34946','FORTPIERCE','FLORIDA','FL');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('32209','JJACKSONVILLE','FLORIDA','FL');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('32824','ORLANDO','FLORIDA','FL');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('330051','Loganville','GEORGIA','GA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('96707','KAPOLEI','HAWAII','HI');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('83657','IDAHO','NAMPA','ID');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('660120','ELGIN','ILLNOIS','IL');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('47348','HARTFORDCITY','INDIANA','IN');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('52748','ELDRIDGE','IOWA','IA');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('66111','KANSASCITY','KANSAS','KS');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('40509','LEXINGTON','KENTUCKY','KY');
Insert into HR.COPART_FACILITY (ZIPCODE,CITY,STATE,ABBREVIATION) values ('70739','GREENWELLSPRINGS','LOUISANA','LA');
